# Generated by Django 4.2.1 on 2023-12-21 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.college')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_years', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('yearly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('certifications', models.CharField(blank=True, max_length=150, null=True)),
                ('total_seats', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('available_seats', models.CharField(blank=True, max_length=100, null=True)),
                ('addmission_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.college')),
            ],
        ),
    ]
