# Generated by Django 4.2.1 on 2024-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_college_thumbnail_collegecourse_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegecourse',
            name='banner',
        ),
        migrations.AddField(
            model_name='college',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
