"""
Django settings for management project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from datetime import datetime, timezone, timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4gb_!_2kvtz3@jq*pdk0xaso9dd93^dybeb!!#+$i+i9cvxi$^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTH_USER_MODEL = "base.User"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'base',
    'inventory',
    'cart',

    #for authentication
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    "corsheaders",

]


#for authentication
REST_FRAMEWORK = {
    
    'DEFAULT_AUTHENTICATION_CLASSES': (
    
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication'
    )

}

PRIVATE_KEY = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAjKTaVkHC6v5D
C1p72j8y3RKkMik4NLePxElRdXmEzkMF52KHMSVXIFe/3629Twz7m/IgY1dA1uMA
q4wFQmRCfUeSJ3tSij4Zm0zySiiQWvl+8AspMPZ3NGcHUGyL0PORKoUOrnht7iNP
6Bk3D3mDnKOzwVANu5hY0VDkJqYUf1Lij2rrHMD4WMNwHlPB+0mwHPrnjhYtFZOZ
kYn0gUHvaE/JQXn9yA6rPQrKfj64Zh9HXhlTx3go2rg0/Fn19HtAPEFkTCnMKLsY
y9sx1HvxhKjb4nu7xyz2/ykmK/KcNJYOFiszfHMICLQBN909/j7+9P530BOwWzly
WvnoeCmxAgMBAAECggEAdA7R9sBzFteptiOLwIdF/JR//fQ2ICi2U7OONclHG6Nv
hol3O+GFjkRyX7ak9CxHuQjAIoF+QBjF7st3tFvWLrVwhEnD7XZiA/E1qfzFAm2z
YK2zLHrUs/kj+KajJoslpGQqmzTSZgBZzHoraKKtLYUmrtxgMkbWhwJzbXFWPZeN
TqHQT4O7Jby/ZriOea+mBa9ktIwrsDJrYYnttCDqmR/C7hFtU/2PSCCG7He0g6+E
U7fMnmscNSmzSPSgNKQzv9GddT8vsiZQigoeMTS2lLIk4/9CPz9MV7OYqswZJEN6
ReQCAI89qoWTQPOG7hY6cT3xHLfvjHuhT0s5JfdYeQKBgQDkd2NW8CwM2ul5nT6e
QXlT0hCnpg2VmYQnoOeBvtnTZZNUqVz50w6714cZJTIgEOE4lJ9cOv0s5RzfSIuV
X80w7lf9wmaeObFUJgXtks1gfQI0ZAMBXn21u/IRB7hNyQnkZBc1bF1mXlshdm8o
Yf5JneorL5OohaNDsAAZsXxoPwKBgQDXwSaQOCTAjGJ89bOKtwW6Qynf5mqvzica
Nhez/8unc5aBvhIg6uV5hMpJVfuO9/UK+BZrjjIwMxLo8IlwV6avYSoNif3ha2nq
+HV9Cwq84TzhiYnQkTNAq3cq7GCDZSjc65QiFsy6+AV9qG8/dTIaRUN6J9AV9MQH
Q5bfA75yDwKBgQDMYnXPP7rYoTp/Hon3P7GPp/xYTngWniiY3xxceOUbdeJQudbA
c+zZZJ2qhBkMkK07VdIey3LUp/6lTZv5vKOvI3o6PKBa6lfWZNGm0E7FA/Bl+Bas
MeEaJJIQZCygAbrExDnzBAemXcD+9ZnJsaiwKQJlMgHRoAQHuLrOQXZ/NwKBgFkI
F4XD5Uafp7SxH1nKlM58ELeYOcY6Z+BlGfrpP3zmMeFwMcLrq64todwJYzloEPJp
1bakgwloyhDd0ZlOUjZk/hmALAftb1PLG5ByEghHWfwn6XrrsB6row1PZbRS9j3T
6Nj4V5t/5aQo8V9aWUaF9oZeD3w/+PSWa5ezz875AoGAFFPiML2GC4f9TLr3iLKL
4JhlvqfEThPSrBj/USuKkNWJQiK0wGP5VVQQTGAVJ8PyFafiJWz1QsEPO9+kshZk
XNu6/jNiNRI2jEZvbcZW2+l50kMAskr5pZq1QZSGGfiuo2+SA1F2qJa1X5cLiajN
YN1HikXgURtUX01aOsIILec=
-----END PRIVATE KEY-----
'''

PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwIyk2lZBwur+Qwtae9o/
Mt0SpDIpODS3j8RJUXV5hM5DBedihzElVyBXv9+tvU8M+5vyIGNXQNbjAKuMBUJk
Qn1Hkid7Uoo+GZtM8kookFr5fvALKTD2dzRnB1Bsi9DzkSqFDq54be4jT+gZNw95
g5yjs8FQDbuYWNFQ5CamFH9S4o9q6xzA+FjDcB5TwftJsBz6544WLRWTmZGJ9IFB
72hPyUF5/cgOqz0Kyn4+uGYfR14ZU8d4KNq4NPxZ9fR7QDxBZEwpzCi7GMvbMdR7
8YSo2+J7u8cs9v8pJivynDSWDhYrM3xzCAi0ATfdPf4+/vT+d9ATsFs5clr56Hgp
sQIDAQAB
-----END PUBLIC KEY-----"""

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "RS256",
    "SIGNING_KEY": PRIVATE_KEY,
    "VERIFYING_KEY": PUBLIC_KEY,
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "base.serializers.MyTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    "corsheaders.middleware.CorsMiddleware",


    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'images/'
STATICFILES_DIRS =[
    BASE_DIR/'static'
]
MEDIA_ROOT = 'static/images'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.email.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'EMAIL'
EMAIL_HOST_PASSWORD = 'PASSWORD'

# for authentication
CORS_ALLOWED_ORIGINS = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
]

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https://\w+\.example\.com$",
# ]
CORS_ALLOW_ALL_ORIGINS= True