# Generated by Django 4.2.1 on 2024-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='courseid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
