# Generated by Django 4.2.1 on 2024-02-23 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_collegecourse_college'),
        ('cart', '0002_cart_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='inventory.collegecourse'),
        ),
    ]
